export const labManualData = [
    { id: 1, branch: 'CSE', semester: 'Semester 1', subject: { code: 'KCS151', name: 'Engineering Physics Lab' }, rating: 4.3, type: 'Lab Manual' },
    { id: 2, branch: 'CSE', semester: 'Semester 1', subject: { code: 'KCS151', name: 'Programming Lab' }, rating: 4.7, type: 'Lab Manual' },
    { id: 3, branch: 'CSE', semester: 'Semester 2', subject: { code: 'KCS251', name: 'Data Structures Lab' }, rating: 4.8, type: 'Lab Manual' },
    { id: 4, branch: 'CSE', semester: 'Semester 2', subject: { code: 'KEC251', name: 'Basic Electronics Lab' }, rating: 4.2, type: 'Lab Manual' },
    { id: 5, branch: 'CSE', semester: 'Semester 3', subject: { code: 'KCS351', name: 'Digital Logic Lab' }, rating: 4.6, type: 'Lab Manual' },
    { id: 6, branch: 'CSE', semester: 'Semester 3', subject: { code: 'KCS352', name: 'OOP Lab' }, rating: 4.9, type: 'Lab Manual' },
    { id: 7, branch: 'CSE', semester: 'Semester 4', subject: { code: 'KCS451', name: 'Database Lab' }, rating: 4.7, type: 'Lab Manual' },
    { id: 8, branch: 'CSE', semester: 'Semester 4', subject: { code: 'KCS452', name: 'OS Lab' }, rating: 4.5, type: 'Lab Manual' },
    { id: 9, branch: 'CSE', semester: 'Semester 5', subject: { code: 'KCS551', name: 'Microprocessors Lab' }, rating: 4.4, type: 'Lab Manual' },
    { id: 10, branch: 'CSE', semester: 'Semester 5', subject: { code: 'KCS552', name: 'Web Tech Lab' }, rating: 4.8, type: 'Lab Manual' },
    { id: 11, branch: 'CSE', semester: 'Semester 6', subject: { code: 'KCS651', name: 'AI/ML Lab' }, rating: 4.9, type: 'Lab Manual' },
    { id: 12, branch: 'CSE', semester: 'Semester 7', subject: { code: 'KCS751', name: 'Project-I' }, rating: 4.3, type: 'Lab Manual' },
    { id: 13, branch: 'CSE', semester: 'Semester 8', subject: { code: 'KCS851', name: 'Project-II' }, rating: 4.6, type: 'Lab Manual' },
    { id: 14, branch: 'ECE', semester: 'Semester 1', subject: { code: 'KPH151', name: 'Engineering Physics Lab' }, rating: 4.2, type: 'Lab Manual' },
    { id: 15, branch: 'ECE', semester: 'Semester 1', subject: { code: 'KCS151', name: 'Programming Lab' }, rating: 4.4, type: 'Lab Manual' },
    { id: 16, branch: 'ECE', semester: 'Semester 2', subject: { code: 'KEC251', name: 'Electronic Devices Lab' }, rating: 4.7, type: 'Lab Manual' },
    { id: 17, branch: 'ECE', semester: 'Semester 2', subject: { code: 'KEC252', name: 'Network Lab' }, rating: 4.3, type: 'Lab Manual' },
    { id: 18, branch: 'ECE', semester: 'Semester 3', subject: { code: 'KEC351', name: 'Digital Lab' }, rating: 4.6, type: 'Lab Manual' },
    { id: 19, branch: 'ECE', semester: 'Semester 3', subject: { code: 'KEC352', name: 'Analog Lab' }, rating: 4.5, type: 'Lab Manual' },
    { id: 20, branch: 'ECE', semester: 'Semester 4', subject: { code: 'KEC451', name: 'Microprocessor Lab' }, rating: 4.8, type: 'Lab Manual' },
    { id: 21, branch: 'ECE', semester: 'Semester 4', subject: { code: 'KEC452', name: 'Communication Lab' }, rating: 4.4, type: 'Lab Manual' },
    { id: 22, branch: 'ECE', semester: 'Semester 5', subject: { code: 'KEC551', name: 'DSP Lab' }, rating: 4.7, type: 'Lab Manual' },
    { id: 23, branch: 'ECE', semester: 'Semester 5', subject: { code: 'KEC552', name: 'VLSI Lab' }, rating: 4.9, type: 'Lab Manual' },
    { id: 24, branch: 'ECE', semester: 'Semester 6', subject: { code: 'KEC651', name: 'Embedded Lab' }, rating: 4.8, type: 'Lab Manual' },
    { id: 25, branch: 'ECE', semester: 'Semester 7', subject: { code: 'KEC751', name: 'Project-I' }, rating: 4.2, type: 'Lab Manual' },
    { id: 26, branch: 'ECE', semester: 'Semester 8', subject: { code: 'KEC851', name: 'Project-II' }, rating: 4.5, type: 'Lab Manual' },
    { id: 27, branch: 'CSE', semester: 'Semester 1', subject: { code: 'KEE151', name: 'Basic Electrical Lab' }, rating: 4.1, type: 'Lab Manual' },
    { id: 28, branch: 'CSE', semester: 'Semester 1', subject: { code: 'KCE151', name: 'Engineering Graphics Lab' }, rating: 4.0, type: 'Lab Manual' },
    { id: 29, branch: 'CSE', semester: 'Semester 2', subject: { code: 'KCH151', name: 'Engineering Chemistry Lab' }, rating: 3.9, type: 'Lab Manual' },
    { id: 30, branch: 'ECE', semester: 'Semester 1', subject: { code: 'KEE151', name: 'Basic Electrical Lab' }, rating: 4.3, type: 'Lab Manual' },
    { id: 31, branch: 'ECE', semester: 'Semester 1', subject: { code: 'KCE151', name: 'Engineering Graphics Lab' }, rating: 4.1, type: 'Lab Manual' },
    { id: 32, branch: 'ECE', semester: 'Semester 2', subject: { code: 'KCH151', name: 'Engineering Chemistry Lab' }, rating: 4.0, type: 'Lab Manual' },
    { id: 33, branch: 'CSE', semester: 'Semester 3', subject: { code: 'KCS353', name: 'Software Engineering Lab' }, rating: 4.4, type: 'Lab Manual' },
    { id: 34, branch: 'CSE', semester: 'Semester 4', subject: { code: 'KCS453', name: 'Computer Architecture Lab' }, rating: 4.2, type: 'Lab Manual' },
    { id: 35, branch: 'CSE', semester: 'Semester 5', subject: { code: 'KCS553', name: 'Compiler Design Lab' }, rating: 4.6, type: 'Lab Manual' },
    { id: 36, branch: 'CSE', semester: 'Semester 5', subject: { code: 'KCS554', name: 'Computer Networks Lab' }, rating: 4.7, type: 'Lab Manual' },
    { id: 37, branch: 'CSE', semester: 'Semester 6', subject: { code: 'KCS652', name: 'Machine Learning Lab' }, rating: 4.8, type: 'Lab Manual' },
    { id: 38, branch: 'CSE', semester: 'Semester 6', subject: { code: 'KCS653', name: 'Distributed Systems Lab' }, rating: 4.3, type: 'Lab Manual' },
    { id: 39, branch: 'ECE', semester: 'Semester 3', subject: { code: 'KEC353', name: 'Electromagnetic Lab' }, rating: 4.1, type: 'Lab Manual' },
    { id: 40, branch: 'ECE', semester: 'Semester 4', subject: { code: 'KEC453', name: 'Control Systems Lab' }, rating: 4.4, type: 'Lab Manual' },
    { id: 41, branch: 'ECE', semester: 'Semester 5', subject: { code: 'KEC553', name: 'Digital Communication Lab' }, rating: 4.5, type: 'Lab Manual' },
    { id: 42, branch: 'ECE', semester: 'Semester 6', subject: { code: 'KEC652', name: 'Optical Communication Lab' }, rating: 4.2, type: 'Lab Manual' },
    { id: 43, branch: 'ECE', semester: 'Semester 6', subject: { code: 'KEC653', name: 'Microwave Engineering Lab' }, rating: 4.6, type: 'Lab Manual' },
    { id: 44, branch: 'ECE', semester: 'Semester 7', subject: { code: 'KEC752', name: 'Wireless Communication Lab' }, rating: 4.3, type: 'Lab Manual' },
    { id: 45, branch: 'CSE', semester: 'Semester 7', subject: { code: 'KCS752', name: 'Cloud Computing Lab' }, rating: 4.7, type: 'Lab Manual' }
];