export const miscData = [
    { id: 1, branch: 'CSE', semester: 'Semester 1', subject: { code: 'KCS101', name: 'Engineering Physics' }, rating: 4.2, type: 'Syllabus' },
    { id: 2, branch: 'CSE', semester: 'Semester 1', subject: { code: 'KAS101', name: 'Engineering Mathematics-I' }, rating: 4.5, type: 'Formula Sheet' },
    { id: 3, branch: 'CSE', semester: 'Semester 1', subject: { code: 'KCS101', name: 'Programming for Problem Solving' }, rating: 4.7, type: 'Cheat Sheet' },
    { id: 4, branch: 'CSE', semester: 'Semester 1', subject: { code: 'KCE101', name: 'Engineering Graphics' }, rating: 4.1, type: 'Reference Material' },
    { id: 5, branch: 'CSE', semester: 'Semester 2', subject: { code: 'KCS201', name: 'Data Structures with C' }, rating: 4.8, type: 'Mind Map' },
    { id: 6, branch: 'CSE', semester: 'Semester 2', subject: { code: 'KAS102', name: 'Engineering Mathematics-II' }, rating: 4.6, type: 'Formula Sheet' },
    { id: 7, branch: 'CSE', semester: 'Semester 2', subject: { code: 'KCH101', name: 'Engineering Chemistry' }, rating: 4.0, type: 'Revision Notes' },
    { id: 8, branch: 'CSE', semester: 'Semester 3', subject: { code: 'KCS302', name: 'Digital Logic Design' }, rating: 4.5, type: 'Project Report' },
    { id: 9, branch: 'CSE', semester: 'Semester 3', subject: { code: 'KCS303', name: 'Object Oriented Programming' }, rating: 4.9, type: 'Presentation Slides' },
    { id: 10, branch: 'CSE', semester: 'Semester 3', subject: { code: 'KCS301', name: 'Discrete Structures' }, rating: 4.3, type: 'Cheat Sheet' },
    { id: 11, branch: 'CSE', semester: 'Semester 4', subject: { code: 'KCS401', name: 'Design & Analysis of Algorithms' }, rating: 4.8, type: 'Mind Map' },
    { id: 12, branch: 'CSE', semester: 'Semester 4', subject: { code: 'KCS403', name: 'Database Management Systems' }, rating: 4.7, type: 'Reference Material' },
    { id: 13, branch: 'CSE', semester: 'Semester 4', subject: { code: 'KCS404', name: 'Operating Systems' }, rating: 4.6, type: 'Revision Timetable' },
    { id: 14, branch: 'CSE', semester: 'Semester 5', subject: { code: 'KCS502', name: 'Computer Networks' }, rating: 4.4, type: 'Syllabus' },
    { id: 15, branch: 'CSE', semester: 'Semester 5', subject: { code: 'KCS503', name: 'Web Technologies' }, rating: 4.9, type: 'Project Report' },
    { id: 16, branch: 'CSE', semester: 'Semester 6', subject: { code: 'KCS601', name: 'Artificial Intelligence' }, rating: 4.8, type: 'Presentation Slides' },
    { id: 17, branch: 'CSE', semester: 'Semester 6', subject: { code: 'KCS602', name: 'Machine Learning' }, rating: 4.7, type: 'Cheat Sheet' },
    { id: 18, branch: 'CSE', semester: 'Semester 7', subject: { code: 'KCS701', name: 'Cloud Computing' }, rating: 4.5, type: 'Reference Material' },
    { id: 19, branch: 'CSE', semester: 'Semester 8', subject: { code: 'KCS801', name: 'Internet of Things' }, rating: 4.3, type: 'Project Report' },
    { id: 20, branch: 'ECE', semester: 'Semester 1', subject: { code: 'KPH101', name: 'Engineering Physics' }, rating: 4.1, type: 'Syllabus' },
    { id: 21, branch: 'ECE', semester: 'Semester 1', subject: { code: 'KAS101', name: 'Engineering Mathematics-I' }, rating: 4.4, type: 'Formula Sheet' },
    { id: 22, branch: 'ECE', semester: 'Semester 1', subject: { code: 'KEE101', name: 'Basic Electrical Engineering' }, rating: 4.2, type: 'Revision Notes' },
    { id: 23, branch: 'ECE', semester: 'Semester 2', subject: { code: 'KEC201', name: 'Electronic Devices & Circuits' }, rating: 4.6, type: 'Mind Map' },
    { id: 24, branch: 'ECE', semester: 'Semester 2', subject: { code: 'KEC202', name: 'Network Analysis' }, rating: 4.3, type: 'Cheat Sheet' },
    { id: 25, branch: 'ECE', semester: 'Semester 3', subject: { code: 'KEC301', name: 'Electromagnetic Theory' }, rating: 4.5, type: 'Formula Sheet' },
    { id: 26, branch: 'ECE', semester: 'Semester 3', subject: { code: 'KEC303', name: 'Analog Electronics' }, rating: 4.7, type: 'Reference Material' },
    { id: 27, branch: 'ECE', semester: 'Semester 3', subject: { code: 'KEC304', name: 'Signals & Systems' }, rating: 4.8, type: 'Presentation Slides' },
    { id: 28, branch: 'ECE', semester: 'Semester 4', subject: { code: 'KEC401', name: 'Linear IC Applications' }, rating: 4.2, type: 'Project Report' },
    { id: 29, branch: 'ECE', semester: 'Semester 4', subject: { code: 'KEC403', name: 'Communication Systems' }, rating: 4.6, type: 'Syllabus' },
    { id: 30, branch: 'ECE', semester: 'Semester 4', subject: { code: 'KEC404', name: 'Control Systems' }, rating: 4.4, type: 'Mind Map' },
    { id: 31, branch: 'ECE', semester: 'Semester 5', subject: { code: 'KEC501', name: 'Digital Signal Processing' }, rating: 4.7, type: 'Cheat Sheet' },
    { id: 32, branch: 'ECE', semester: 'Semester 5', subject: { code: 'KEC502', name: 'VLSI Design' }, rating: 4.9, type: 'Reference Material' },
    { id: 33, branch: 'ECE', semester: 'Semester 5', subject: { code: 'KEC503', name: 'Digital Communication' }, rating: 4.5, type: 'Revision Notes' },
    { id: 34, branch: 'ECE', semester: 'Semester 6', subject: { code: 'KEC601', name: 'Embedded Systems' }, rating: 4.8, type: 'Project Report' },
    { id: 35, branch: 'ECE', semester: 'Semester 6', subject: { code: 'KEC602', name: 'Optical Communication' }, rating: 4.3, type: 'Presentation Slides' },
    { id: 36, branch: 'ECE', semester: 'Semester 7', subject: { code: 'KEC701', name: 'Wireless Communication' }, rating: 4.4, type: 'Syllabus' },
    { id: 37, branch: 'CSE', semester: 'Semester 2', subject: { code: 'KEN101', name: 'Environmental Science' }, rating: 3.9, type: 'Revision Timetable' },
    { id: 38, branch: 'CSE', semester: 'Semester 3', subject: { code: 'KCS304', name: 'Computer Organization' }, rating: 4.2, type: 'Formula Sheet' },
    { id: 39, branch: 'CSE', semester: 'Semester 4', subject: { code: 'KCS402', name: 'Computer Architecture' }, rating: 4.1, type: 'Mind Map' },
    { id: 40, branch: 'CSE', semester: 'Semester 5', subject: { code: 'KCS501', name: 'Compiler Design' }, rating: 4.6, type: 'Reference Material' },
    { id: 41, branch: 'ECE', semester: 'Semester 2', subject: { code: 'KAS102', name: 'Engineering Mathematics-II' }, rating: 4.3, type: 'Formula Sheet' },
    { id: 42, branch: 'ECE', semester: 'Semester 3', subject: { code: 'KEC302', name: 'Digital Logic Design' }, rating: 4.5, type: 'Cheat Sheet' },
    { id: 43, branch: 'ECE', semester: 'Semester 4', subject: { code: 'KEC402', name: 'Microprocessors' }, rating: 4.4, type: 'Revision Notes' },
    { id: 44, branch: 'ECE', semester: 'Semester 6', subject: { code: 'KEC603', name: 'Microwave Engineering' }, rating: 4.2, type: 'Mind Map' },
    { id: 45, branch: 'CSE', semester: 'Semester 6', subject: { code: 'KCS603', name: 'Distributed Systems' }, rating: 4.7, type: 'Project Report' }
];